name: movetopia
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: 3.29.2

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  cupertino_icons: ^1.0.6
  riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  health: ^12.1.0
  intl: any
  flutter_localizations:
    sdk: flutter
  logging: ^1.2.0
  go_router: ^14.8.1
  flutter_hooks: ^0.20.5
  percent_indicator: ^4.2.3
  shared_preferences: ^2.3.1
  fl_chart: ^0.68.0
  installed_apps: ^1.5.2
  package_info_plus: ^8.3.0
  sqflite: ^2.4.1
  path: ^1.9.0
  table_calendar: ^3.1.0
  activity_tracking:
    git:
      url: https://github.com/Jozys/activity_tracking.git
      ref: main
  permission_handler: ^11.4.0
  smooth_page_indicator: ^1.1.0
  app_settings: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  go_router_builder: any
  build_runner: any
  build_verify: any
  flutter_launcher_icons: 0.14.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/app_icon.png
    - assets/data/badges.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
