name: "Build APK"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-22.04
    steps:
      - name: "Clone the repository"
        uses: actions/checkout@v4
      - name: "Set up Java environment"
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: 22
      - name: "Set Up Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.1 # path to pubspec.yaml

      - name: "Install flutter dependencies"
        run: flutter pub get
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: |
            - build/app/outputs/flutter-apk/app-release.apk
      - name: Get current date
        run: |
          echo "{date}={$(date +'%Y-%m-%d')}" >> $GITHUB_STATE
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.date }}
          release_name: Release ${{ env.date }}