name: "PR Check - Build Only"
on:
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  check-skip-conditions:
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{ steps.check-labels.outputs.should-skip }}
    steps:
      - name: Check PR labels
        id: check-labels
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.pull_request?.labels || [];
            const skipLabels = ['docs-only', 'no-build'];
            const shouldSkip = labels.some(label => skipLabels.includes(label.name));
            console.log(`Labels: ${labels.map(l => l.name).join(', ')}`);
            console.log(`Should skip build: ${shouldSkip}`);
            return shouldSkip;

  build-check:
    name: "Build Check"
    needs: check-skip-conditions
    if: ${{ needs.check-skip-conditions.outputs.should-skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up Java"
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "22"

      - name: "Set up Gradle"
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper

      - name: "Set up Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - name: "Setup Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          working-directory: 'android'
          bundler-cache: true

      - name: "Run Fastlane Debug Build"
        id: fastlane
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: build_debug
          subdirectory: android
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: "Build Status"
        run: echo "Debug build completed - PR check passed!" 